# (C) Copyright 2025 Meteorolgisk Institutt
#

# VIND bundle for JEDI
cmake_minimum_required( VERSION 3.12 FATAL_ERROR )
find_package( ecbuild 3.6 REQUIRED HINTS ${CMAKE_CURRENT_SOURCE_DIR} ${CMAKE_CURRENT_SOURCE_DIR}/../ecbuild)
project( vind-bundle VERSION 8.0.0 LANGUAGES C CXX Fortran )
list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake")
include( ecbuild_bundle )

# Default release mode
set( ECBUILD_DEFAULT_BUILD_TYPE Release )

# Options
option( ENABLE_MPI "Compile with MPI" ON )
option( ENABLE_OMP "Compile with OpenMP" ON )
option( ENABLE_CUDA "Compile with CUDA" OFF )
option( ENABLE_MKL "Compile with MKL" OFF )
option( ENABLE_TRANSI "Compile TransI C-interface to trans" ON )
option( ENABLE_ETRANS "Include Limited-Area-Model Transforms" ON )
option( ENABLE_JEDI_MODEL_DATA "Obtain saber/vader test data from jedi-model-data repository (vs tarball)" ON )
option( ENABLE_PYBIND11 "Compile with pybind11" OFF )
option( ENABLE_TORCH "Compile with torch" OFF )
option( ENABLE_IODA_DATA "Obtain ioda test data from ioda-data repository (vs tarball)" ON )
option( ENABLE_UFO_DATA "Obtain ufo test data from ufo-data repository (vs tarball)" ON )
option( BUILD_IODA_CONVERTERS "Build IODA Converters" OFF )

# What to compile?
option( ENABLE_SABER "Compile SABER" ON )
option( ENABLE_OBS "Compile IODA/UFO" ON )
option( ENABLE_CRTM "Compile CRTM" OFF )

# What tests to run?
option( ENABLE_AQ_TESTS "Run aq tests" OFF )
option( ENABLE_GENINT_TESTS "Run genint tests" ON )
option( ENABLE_GLB_TESTS "Run global tests" ON )
option( ENABLE_MONARCH_TESTS "Run regional monarch tests" OFF )
option( ENABLE_MONGLOB_TESTS "Run global monarch tests" OFF )
option( ENABLE_REG_TESTS "Run regional tests" ON )

# Setup
link_directories( ${CMAKE_CURRENT_BINARY_DIR}/lib )
include( GNUInstallDirs )
set( INSTALL_LIB_DIR ${CMAKE_INSTALL_LIBDIR} CACHE STRING "Library installation directory" FORCE )
set( ECBUILD_DEFAULT_BUILD_TYPE Release CACHE STRING "ECBuild default build type" FORCE )
set( CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin )
set( CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib )
set( CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib )
set( CMAKE_INSTALL_RPATH_USE_LINK_PATH ON )
set( CMAKE_BUILD_WITH_INSTALL_RPATH ON )

# Initialize bundle
ecbuild_bundle_initialize()

# Use external jedi-cmake or build in bundle
if( DEFINED ENV{jedi_cmake_ROOT} )
    include( $ENV{jedi_cmake_ROOT}/share/jedicmake/Functions/git_functions.cmake )
    list( APPEND CMAKE_MODULE_PATH $ENV{jedi_cmake_ROOT}/share/jedicmake/Modules )
    message( INFO "CMAKE_MODULE_PATH" )
else()
    if (DEFINED ENV{VIND_BUNDLE_SRC_DIR})
      ecbuild_bundle( PROJECT jedicmake SOURCE $ENV{VIND_BUNDLE_SRC_DIR}/jedicmake )
    else()
      ecbuild_bundle( PROJECT jedicmake GIT "https://github.com/jcsda/jedi-cmake.git" TAG 40d521f9a2d796fcbc6234d77abceeffefb8eb7f RECURSIVE )
    endif()
    include( jedicmake/cmake/Functions/git_functions.cmake )
    list( APPEND CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/jedicmake/CMakeModules/Modules )
endif()

if (DEFINED ENV{VIND_BUNDLE_SRC_DIR})
  # ECMWF tools
  ecbuild_bundle( PROJECT eckit SOURCE $ENV{VIND_BUNDLE_SRC_DIR}/eckit )
  ecbuild_bundle( PROJECT fckit SOURCE $ENV{VIND_BUNDLE_SRC_DIR}/fckit )
  ecbuild_bundle( PROJECT fiat SOURCE $ENV{VIND_BUNDLE_SRC_DIR}/fiat )
  ecbuild_bundle( PROJECT ectrans SOURCE $ENV{VIND_BUNDLE_SRC_DIR}/ectrans )
  ecbuild_bundle( PROJECT atlas SOURCE $ENV{VIND_BUNDLE_SRC_DIR}/atlas )

  # oops
  ecbuild_bundle( PROJECT oops SOURCE $ENV{VIND_BUNDLE_SRC_DIR}/oops )

  # jedi-data
  ecbuild_bundle( PROJECT jedi-model-data SOURCE $ENV{VIND_BUNDLE_SRC_DIR}/jedi-model-data )

  # vader
  ecbuild_bundle( PROJECT vader SOURCE $ENV{VIND_BUNDLE_SRC_DIR}/vader )

  if( ENABLE_SABER )
    # gsibec
    ecbuild_bundle( PROJECT gsibec SOURCE $ENV{VIND_BUNDLE_SRC_DIR}/gsibec )

    # saber
    ecbuild_bundle( PROJECT saber SOURCE $ENV{VIND_BUNDLE_SRC_DIR}/saber )
  endif()

  if( ENABLE_CRTM )
    # crtm
    ecbuild_bundle( PROJECT crtm SOURCE $ENV{VIND_BUNDLE_SRC_DIR}/crtm )
  endif()

  if( ENABLE_OBS )
    # ioda
    ecbuild_bundle( PROJECT ioda SOURCE $ENV{VIND_BUNDLE_SRC_DIR}/ioda )
    if( BUILD_IODA_CONVERTERS )
        ecbuild_bundle( PROJECT iodaconv GIT SOURCE $ENV{VIND_BUNDLE_SRC_DIR}/iodaconv )
    endif()

    # ufo
    ecbuild_bundle( PROJECT ufo SOURCE $ENV{VIND_BUNDLE_SRC_DIR}/ufo )
  endif()
else()
  # ECMWF tools
  ecbuild_bundle( PROJECT eckit GIT "https://github.com/ecmwf/eckit.git" TAG 1.32.3 )
  ecbuild_bundle( PROJECT fckit GIT "https://github.com/ecmwf/fckit.git" TAG 0.14.1 )
  ecbuild_bundle( PROJECT fiat GIT "https://github.com/ecmwf-ifs/fiat.git" TAG 1.6.1 )
  #ecbuild_bundle( PROJECT ectrans GIT "https://github.com/ecmwf-ifs/ectrans.git" TAG 3094b24ec9c1862772e2b02f4e06c797247d57fc )
  ecbuild_bundle( PROJECT ectrans GIT "https://github.com/ecmwf-ifs/ectrans.git" TAG 1.7.0 )
  ecbuild_bundle( PROJECT atlas GIT "https://github.com/ecmwf/atlas.git" TAG 0.44.1 )

  # oops
  ecbuild_bundle( PROJECT oops GIT "https://github.com/jcsda/oops.git" BRANCH develop UPDATE )

  # jedi-data
  ecbuild_bundle( PROJECT jedi-model-data GIT "https://github.com/jcsda-internal/jedi-model-data.git" BRANCH feature/nicas_article UPDATE )
  
  # vader
  ecbuild_bundle( PROJECT vader GIT "https://github.com/jcsda/vader.git" BRANCH develop UPDATE )

  if( ENABLE_SABER )
    # gsibec
    ecbuild_bundle( PROJECT gsibec GIT "https://github.com/benjaminmenetrier/GSIbec.git" BRANCH bugfix/fortran_line_length UPDATE )

    # saber
    ecbuild_bundle( PROJECT saber GIT "https://github.com/benjaminmenetrier/saber.git" BRANCH feature/nicas_article UPDATE )
  endif()
  
  if( ENABLE_CRTM )
    # crtm
    ecbuild_bundle( PROJECT crtm GIT "https://github.com/jcsda/CRTMv3.git" BRANCH develop UPDATE )
  endif()

  if( ENABLE_OBS )
    # ioda-data
    ecbuild_bundle( PROJECT ioda-data GIT "https://github.com/jcsda-internal/ioda-data.git" BRANCH develop UPDATE )

    # ioda
    ecbuild_bundle( PROJECT ioda GIT "https://github.com/jcsda/ioda.git" BRANCH develop UPDATE )

    # ioda-converters
    if( BUILD_IODA_CONVERTERS )
      ecbuild_bundle( PROJECT iodaconv GIT "https://github.com/jcsda/ioda-converters.git" BRANCH develop UPDATE )
    endif()

    # ufo-data
    ecbuild_bundle( PROJECT ufo-data GIT "https://github.com/jcsda-internal/ufo-data.git" BRANCH develop UPDATE )

    # ufo
    ecbuild_bundle( PROJECT ufo GIT "https://github.com/jcsda/ufo.git" BRANCH develop UPDATE )
  endif()
endif()

# vind
ecbuild_bundle( PROJECT vind SOURCE ..)

ecbuild_bundle_finalize()
